# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cnemegha <cnemegha@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/20 12:01:58 by cnemegha          #+#    #+#              #
#    Updated: 2015/09/22 11:22:34 by cnemegha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Crypto_Mania

FILE =  main.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(FILE)

clean:
	rm -r $(NAME)

re: clean all
